# Generated by Django 5.1.6 on 2025-04-15 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital_email_snapshot', models.EmailField(blank=True, max_length=254, null=True)),
                ('hospital_contact_snapshot', models.CharField(blank=True, max_length=15, null=True)),
                ('hospital_address_snapshot', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4)),
                ('units_requested', models.FloatField()),
                ('units_approved', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'user_type': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_handled_requests', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, limit_choices_to={'user_type': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
