# Generated by Django 5.1.7 on 2025-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hospitalbloodrequest_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
